//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iStone.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UtilResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iStone.Util.UtilResource", typeof(UtilResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123456789.
        /// </summary>
        internal static string JSNumbers {
            get {
                return ResourceManager.GetString("JSNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ªµºÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ.
        /// </summary>
        internal static string JSReplacers {
            get {
                return ResourceManager.GetString("JSReplacers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +-*/%=&gt;&lt;&amp;|^~!,;[]{}():. ?.
        /// </summary>
        internal static string JSSeparators {
            get {
                return ResourceManager.GetString("JSSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement, break
        ///Statement, catch
        ///Statement, @cc_on
        ///Statement, continue
        ///Statement, do
        ///Statement, for
        ///Statement, in
        ///Statement, finally
        ///Statement, function
        ///Statement, @if
        ///Statement, if
        ///Statement, else
        ///Statement, return
        ///Statement, @set
        ///Statement, switch
        ///Statement, case
        ///Statement, default
        ///Statement, this
        ///Statement, throw
        ///Statement, try
        ///Statement, var
        ///Statement, while
        ///Statement, with
        ///Operator, delete
        ///Operator, false
        ///Operator, instanceof
        ///Operator, new
        ///Operator, null
        ///Operator, true
        ///Ope [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemNames {
            get {
                return ResourceManager.GetString("SystemNames", resourceCulture);
            }
        }
    }
}
